-- HISTORICO JA APLICADO. NAO EXECUTAR EM PRODUCAO.
-- Fonte: supabase_migrations.schema_migrations; comandos de dados/DO omitidos.

create table if not exists public.meta_ad_accounts (
  id uuid primary key default extensions.uuid_generate_v4(),
  client_id uuid null references public.clients(id) on delete set null,
  meta_account_id text not null unique,
  account_id text,
  name text,
  currency text,
  timezone_name text,
  account_status integer,
  is_selected boolean not null default false,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meta_campaigns (
  id uuid primary key default extensions.uuid_generate_v4(),
  ad_account_id uuid not null references public.meta_ad_accounts(id) on delete cascade,
  meta_campaign_id text not null unique,
  name text,
  status text,
  effective_status text,
  objective text,
  buying_type text,
  daily_budget numeric,
  lifetime_budget numeric,
  start_time timestamptz,
  stop_time timestamptz,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  last_synced_at timestamptz not null default now()
);

create table if not exists public.meta_adsets (
  id uuid primary key default extensions.uuid_generate_v4(),
  ad_account_id uuid not null references public.meta_ad_accounts(id) on delete cascade,
  campaign_id uuid null references public.meta_campaigns(id) on delete cascade,
  meta_adset_id text not null unique,
  meta_campaign_id text,
  name text,
  status text,
  effective_status text,
  optimization_goal text,
  billing_event text,
  daily_budget numeric,
  lifetime_budget numeric,
  targeting jsonb,
  start_time timestamptz,
  end_time timestamptz,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  last_synced_at timestamptz not null default now()
);

create table if not exists public.meta_ads (
  id uuid primary key default extensions.uuid_generate_v4(),
  ad_account_id uuid not null references public.meta_ad_accounts(id) on delete cascade,
  campaign_id uuid null references public.meta_campaigns(id) on delete cascade,
  adset_id uuid null references public.meta_adsets(id) on delete cascade,
  meta_ad_id text not null unique,
  meta_campaign_id text,
  meta_adset_id text,
  name text,
  status text,
  effective_status text,
  creative_id text,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  last_synced_at timestamptz not null default now()
);

create table if not exists public.meta_insights_daily (
  id bigint generated by default as identity primary key,
  ad_account_id uuid not null references public.meta_ad_accounts(id) on delete cascade,
  level text not null check (level in ('account','campaign','adset','ad')),
  entity_id text not null,
  entity_name text,
  date_start date not null,
  date_stop date not null,
  spend numeric not null default 0,
  impressions bigint not null default 0,
  reach bigint not null default 0,
  frequency numeric,
  clicks bigint not null default 0,
  inline_link_clicks bigint not null default 0,
  ctr numeric,
  cpc numeric,
  cpm numeric,
  actions jsonb not null default '[]'::jsonb,
  action_values jsonb not null default '[]'::jsonb,
  cost_per_action_type jsonb not null default '[]'::jsonb,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  unique (ad_account_id, level, entity_id, date_start, date_stop)
);

create table if not exists public.meta_sync_runs (
  id uuid primary key default extensions.uuid_generate_v4(),
  mode text not null check (mode in ('discover','sync')),
  ad_account_id uuid null references public.meta_ad_accounts(id) on delete set null,
  status text not null check (status in ('running','success','partial','error')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  rows_upserted integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  error_message text
);

create index if not exists meta_ad_accounts_client_id_idx on public.meta_ad_accounts(client_id);

create index if not exists meta_campaigns_account_idx on public.meta_campaigns(ad_account_id);

create index if not exists meta_adsets_account_idx on public.meta_adsets(ad_account_id);

create index if not exists meta_ads_account_idx on public.meta_ads(ad_account_id);

create index if not exists meta_insights_daily_account_date_idx on public.meta_insights_daily(ad_account_id, date_start desc);

create index if not exists meta_insights_daily_level_entity_idx on public.meta_insights_daily(level, entity_id, date_start desc);

alter table public.meta_ad_accounts enable row level security;

alter table public.meta_campaigns enable row level security;

alter table public.meta_adsets enable row level security;

alter table public.meta_ads enable row level security;

alter table public.meta_insights_daily enable row level security;

alter table public.meta_sync_runs enable row level security;

revoke all on public.meta_ad_accounts from anon, authenticated;

revoke all on public.meta_campaigns from anon, authenticated;

revoke all on public.meta_adsets from anon, authenticated;

revoke all on public.meta_ads from anon, authenticated;

revoke all on public.meta_insights_daily from anon, authenticated;

revoke all on public.meta_sync_runs from anon, authenticated;
